[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd api && python3 -m venv venv",
  "cd api && source venv/bin/activate && python3 -m pip install --upgrade pip",
  "cd api && source venv/bin/activate && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd api && source venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
